// packages/react/src/expose-component.fn.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { s, θtypes } from '@hashbrownai/core';
import type { ComponentType } from 'react';

export type ComponentPropSchema<T> = θtypes.Prettify<
  T extends ComponentType<infer P>
    ? {
        [K in keyof P]?: s.Schema<P[K]>;
      }
    : never
>;

export interface ExposedComponent<T extends ComponentType<any>> {
  component: T;
  name: string;
  description: string;
  children?: 'any' | ExposedComponent<any>[] | false;
  props?: ComponentPropSchema<T>;
}

/**
 * Exposes a component by combining it with additional configuration details.
 *
 * @template T - The type of the component.
 * @param {T} component - The React component to be exposed.
 * @param {Prettify<Omit<ExposedComponent<T>, 'component'>>} config - The configuration object for the component, excluding the component itself.
 * @returns {ExposedComponent<T>} - An object representing the exposed component, including the component and its configuration.
 */
export function exposeComponent<T extends ComponentType<any>>(
  component: T,
  config: θtypes.Prettify<Omit<ExposedComponent<T>, 'component'>>,
): ExposedComponent<T> {
  return {
    component,
    ...config,
  };
}

// packages/angular/src/expose-component.fn.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { reflectComponentType } from '@angular/core';
import { s, θtypes } from '@hashbrownai/core';

type AngularSignalLike<T> = () => T;

export type ComponentPropSchema<T> = θtypes.Prettify<
  T extends { new (...args: any[]): infer P }
    ? {
        [K in keyof P]?: P[K] extends AngularSignalLike<infer U>
          ? s.Schema<U>
          : s.Schema<P[K]>;
      }
    : never
>;

export interface ExposedComponent<T extends { new (...args: any[]): any }> {
  component: T;
  name: string;
  description: string;
  children?: 'any' | ExposedComponent<any>[] | false;
  props?: ComponentPropSchema<T>;
}

/**
 * Exposes a component by combining it with additional configuration details.
 *
 * @template T - The type of the Angular component.
 * @param {T} component - The Angular component to be exposed.
 * @param {Prettify<Omit<ExposedComponent<T>, 'component' | 'name'>>} config - The configuration object for the component, excluding the component itself.
 * @returns {ExposedComponent<T>} - An object representing the exposed component, including the component and its configuration.
 */
export function exposeComponent<T extends { new (...args: any[]): any }>(
  component: T,
  config: θtypes.Prettify<
    Omit<ExposedComponent<T>, 'component' | 'name' | 'props'> & {
      input?: ComponentPropSchema<T>;
    }
  >,
): ExposedComponent<T> {
  const reflected = reflectComponentType(component);

  if (!reflected?.selector) {
    throw new Error(`Could not reflect component: ${component}`);
  }

  const { input, ...rest } = config;

  return {
    component,
    ...rest,
    props: input,
    name: reflected?.selector,
  };
}
