// packages/angular/src/utils/create-tool.fn.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Chat, s } from '@hashbrownai/core';
import {
  inject,
  Injector,
  runInInjectionContext,
  untracked,
} from '@angular/core';

/**
 * Creates a tool with a schema.
 *
 * @param input - The input for the tool.
 * @param input.name - The name of the tool.
 * @param input.description - The description of the tool.
 * @param input.schema - The schema of the tool.
 * @param input.handler - The handler of the tool.
 * @param Name - The name of the tool.
 * @param Schema - The schema of the tool.
 * @param Result - The result of the tool.
 * @returns The tool.
 */
export function createTool<
  const Name extends string,
  Schema extends s.HashbrownType,
  Result,
>(input: {
  name: Name;
  description: string;
  schema: Schema;
  handler: (
    input: s.Infer<Schema>,
    abortSignal: AbortSignal,
  ) => Promise<Result>;
}): Chat.Tool<Name, s.Infer<Schema>, Result>;

/**
 * Creates a tool with a unknown JSON schema.
 *
 * @param input - The input for the tool.
 * @param input.name - The name of the tool.
 * @param input.description - The description of the tool.
 * @param input.schema - The schema of the tool.
 * @param input.handler - The handler of the tool.
 * @param Name - The name of the tool.
 * @param Schema - The schema of the tool.
 * @param Result - The result of the tool.
 * @returns The tool.
 */
export function createTool<const Name extends string, Result>(input: {
  name: Name;
  description: string;
  schema: object;
  handler: (input: any, abortSignal: AbortSignal) => Promise<Result>;
}): Chat.Tool<Name, any, Result>;

/**
 * Creates a tool without a schema.
 *
 * @param input - The input for the tool.
 * @param input.name - The name of the tool.
 * @param input.description - The description of the tool.
 * @param input.handler - The handler of the tool.
 * @param Name - The name of the tool.
 * @param Result - The result of the tool.
 * @returns The tool.
 */
export function createTool<const Name extends string, Result>(input: {
  name: Name;
  description: string;
  handler: (abortSignal: AbortSignal) => Promise<Result>;
}): Chat.Tool<Name, void, Result>;

export function createTool(
  input:
    | {
        name: string;
        description: string;
        schema: s.HashbrownType;
        handler: (a: unknown, s: AbortSignal) => Promise<unknown>;
      }
    | {
        name: string;
        description: string;
        handler: (s: AbortSignal) => Promise<unknown>;
      }
    | {
        name: string;
        description: string;
        schema: object;
        handler: (a: unknown, s: AbortSignal) => Promise<unknown>;
      },
): unknown {
  const injector = inject(Injector);

  if ('schema' in input) {
    const { name, description, schema, handler } = input;
    return {
      name,
      description,
      schema,
      handler: (args: unknown, abortSignal: AbortSignal) =>
        untracked(() =>
          runInInjectionContext(injector, () => handler(args, abortSignal)),
        ),
    };
  } else {
    const { name, description, handler } = input;
    return {
      name,
      description,
      schema: s.object('Empty Object', {}),
      handler: (_: void, abortSignal: AbortSignal) =>
        untracked(() =>
          runInInjectionContext(injector, () => handler(abortSignal)),
        ),
    };
  }
}

// packages/react/src/create-tool.fn.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Chat, s } from '@hashbrownai/core';
import { useEffect, useMemo, useRef } from 'react';

/**
 * Input for the createToolWithArgs function.
 */
export interface CreateToolWithArgsInput<
  Name extends string,
  Schema extends s.HashbrownType,
  Result,
> {
  name: Name;
  description: string;
  schema: Schema;
  handler: (input: s.Infer<Schema>) => Promise<Result>;
}

export function createToolWithArgs<
  const Name extends string,
  Schema extends s.HashbrownType,
  Result,
>(
  input: CreateToolWithArgsInput<Name, Schema, Result>,
): Chat.Tool<Name, s.Infer<Schema>, Result> {
  return {
    name: input.name,
    description: input.description,
    schema: input.schema,
    handler: input.handler,
  };
}

/**
 * Input for the createTool function.
 */
export interface CreateToolInput<Name extends string, Result> {
  name: Name;
  description: string;
  handler: () => Promise<Result>;
}

/**
 * Creates a tool with a handler that takes no arguments.
 *
 * @param input
 * @returns
 */
export function createTool<const Name extends string, Result>(
  input: CreateToolInput<Name, Result>,
): Chat.Tool<Name, void, Result> {
  return {
    name: input.name,
    description: input.description,
    schema: s.object('Empty Object', {}),
    handler: input.handler,
  };
}

/**
 * Use tools in a React component.
 *
 * @param tools
 * @returns
 */
export function useTools<Tools extends Chat.AnyTool>(tools: Tools[]) {
  const callbacks = useRef<
    Record<string, (input: any, abortSignal: AbortSignal) => Promise<unknown>>
  >({});

  useEffect(() => {
    for (const tool of tools) {
      callbacks.current[tool.name] = tool.handler;
    }
  }, [tools]);

  return useMemo(() => {
    return tools.map((tool) => ({
      ...tool,
      handler: (input: any, abortSignal: AbortSignal) =>
        callbacks.current[tool.name](input, abortSignal),
    }));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [...tools.map((tool) => tool.name)]);
}
