// samples/finance/react/src/app/chart/AiClarification.tsx
import { s } from '@hashbrownai/core';
import type { ComponentPropSchema } from '@hashbrownai/react';
import { AiToastNotification } from './AiToastNotification';

export interface AiClarificationProps {
  title: string;
  message: string;
}

const AiClarificationComponent = ({
  title,
  message,
}: AiClarificationProps) => (
  <AiToastNotification title={title} message={message} type="info" />
);

const schema: ComponentPropSchema<typeof AiClarificationComponent> = {
  title: s.streaming.string('The title of the clarification message'),
  message: s.streaming.string('The message of the clarification message'),
};

export const AiClarification = Object.assign(AiClarificationComponent, {
  schema,
});

// samples/finance/angular/src/app/chart/AiClarification.ts
import { Component, input } from '@angular/core';
import { s } from '@hashbrownai/core';
import { ComponentPropSchema } from '@hashbrownai/angular';
import { AiToastNotification } from './AiToastNotification';

@Component({
  selector: 'app-ai-clarification',
  imports: [AiToastNotification],
  template: `
    <app-ai-toast-notification
      [title]="title()"
      [message]="message()"
      type="info"
    ></app-ai-toast-notification>
  `,
})
export class AiClarification {
  title = input.required<string>();
  message = input.required<string>();

  static readonly schema: ComponentPropSchema<typeof AiClarification> = {
    title: s.streaming.string('The title of the clarification message'),
    message: s.streaming.string('The message of the clarification message'),
  };
}
