// samples/finance/angular/src/app/chart/AiRefusal.ts
import { Component, input } from '@angular/core';
import { s } from '@hashbrownai/core';
import { ComponentPropSchema } from '@hashbrownai/angular';
import { AiToastNotification } from './AiToastNotification';

@Component({
  selector: 'app-ai-refusal',
  imports: [AiToastNotification],
  template: `
    <app-ai-toast-notification
      [title]="title()"
      [message]="message()"
      type="refusal"
    ></app-ai-toast-notification>
  `,
})
export class AiRefusal {
  title = input.required<string>();
  message = input.required<string>();

  static readonly schema: ComponentPropSchema<typeof AiRefusal> = {
    title: s.streaming.string('The title of the refusal message'),
    message: s.streaming.string('The message of the refusal message'),
  };
}

// samples/finance/react/src/app/chart/AiRefusal.tsx
import { s } from '@hashbrownai/core';
import type { ComponentPropSchema } from '@hashbrownai/react';
import { AiToastNotification } from './AiToastNotification';

export interface AiRefusalProps {
  title: string;
  message: string;
}

const AiRefusalComponent = ({ title, message }: AiRefusalProps) => (
  <AiToastNotification title={title} message={message} type="refusal" />
);

const schema: ComponentPropSchema<typeof AiRefusalComponent> = {
  title: s.streaming.string('The title of the refusal message'),
  message: s.streaming.string('The message of the refusal message'),
};

export const AiRefusal = Object.assign(AiRefusalComponent, { schema });
