// samples/finance/angular/src/app/chart/AiSuccess.ts
import { Component, input } from '@angular/core';
import { s } from '@hashbrownai/core';
import { ComponentPropSchema } from '@hashbrownai/angular';
import { AiToastNotification } from './AiToastNotification';

@Component({
  selector: 'app-ai-success',
  imports: [AiToastNotification],
  template: `
    <app-ai-toast-notification
      [title]="title()"
      [message]="message()"
      type="success"
    ></app-ai-toast-notification>
  `,
})
export class AiSuccess {
  title = input.required<string>();
  message = input.required<string>();

  static readonly schema: ComponentPropSchema<typeof AiSuccess> = {
    title: s.streaming.string('The title of the success message'),
    message: s.streaming.string('The message of the success message'),
  };
}

// samples/finance/react/src/app/chart/AiSuccess.tsx
import { s } from '@hashbrownai/core';
import type { ComponentPropSchema } from '@hashbrownai/react';
import { AiToastNotification } from './AiToastNotification';

export interface AiSuccessProps {
  title: string;
  message: string;
}

const AiSuccessComponent = ({ title, message }: AiSuccessProps) => (
  <AiToastNotification title={title} message={message} type="success" />
);

const schema: ComponentPropSchema<typeof AiSuccessComponent> = {
  title: s.streaming.string('The title of the success message'),
  message: s.streaming.string('The message of the success message'),
};

export const AiSuccess = Object.assign(AiSuccessComponent, { schema });
